# Site settings
title: "Saravanan Selvaraju"
email: saravanan036@outlook.com
description: "Software Engineer"
baseurl: ""
url: "http://www.saravanan.gq/"
title_description: "Studying Computer Science and Engineering | Writes code | Software Developer."
title_image: "http://www.saravanan.gq/images/avatar.jpg"
google_analytics: "UA-112928594-2"
disqus_account: 
github_repository: https://github.com/saravanan-selvaraju
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: iamsaravanan98
github_username:  saravanan-selvaraju
instagram_username: saravanan_selvaraju
reddit_username: 
linkedin_link: https://www.linkedin.com/in/saravanan-selvaraju/
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link: https://www.facebook.com/saravanan.selvaraju.36

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> using <a href=\"http://jekyllrb.com\">Jekyllrb</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/saravanan-selvaraju\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
